cinetix/urls.py
from django.urls import path

from .views import *

app_name = "cinetix"

urlpatterns = [
    path('film-list/', FilmListView.as_view(), name='film-list'),
    path('film-list/nouveau/', FilmCreateView.as_view(), name='film-create'),
    path('film-list/<str:id_film>/modification/', FilmUpdateView.as_view(), name='film-update'),
    path('film-list/<str:id_film>/suppresion/', FilmDeleteView.as_view(), name='film-delete'),
    path('projection-list/', ProjListView.as_view(), name='projection-list'),
    path('projection-list/nouveau/', ProjCreateView.as_view(), name='projection-create'),
]

cinetix_project/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import login_page, test_page


urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', test_page, name='test'),
    path('', login_page, name='login'),
    path('cinetix/', include('cinetix.urls')),
]

cinetix/models.py
from django.db import models
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField

class Film(models.Model):
    id_film = models.AutoField(primary_key=True)
    titre = models.CharField(max_length=255)
    genres = ArrayField(
        models.CharField(max_length=50),
        size=3,
        blank=True,
        default=list,
    )
    acteur = models.CharField(max_length=255)
    synopsis = models.CharField(max_length=255)
    evaluation = models.FloatField()
    trailer = models.FileField(upload_to='static/video/trailer')
    posteur = models.ImageField(upload_to='static/img/film/')
    commentaires = models.CharField(max_length=255)
    
    def __str__(self):
        return self.titre
    
    def get_absolute_url(self):
        return reverse('film-list')
    
    
    
class Projection(models.Model):
    id_proj = models.AutoField(primary_key=True)
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name="projections")
    type_proj = models.CharField(max_length=20, choices=[
        ('FC', 'Film Complet'),
        ('FAP', 'Avant-Première'),
        ('FP', 'Prochainement'),
    ])
    date_proj = models.CharField(max_length=255)
    heure_proj = models.CharField(max_length=255)
    paf_proj = models.FloatField()
    desc_proj = models.CharField(max_length=255)
    place_proj = ArrayField(
        models.CharField(max_length=10),
        size=92,
        blank=True,
        default=list,
    )
    
    
    def __str__(self):
        return self.film.titre

cinetix/forms.py
from django import forms
from .models import Projection, Film

class ProjectionForm(forms.ModelForm):
    film = forms.ModelChoiceField(
        queryset=Film.objects.all(),
        empty_label="Choisir un film",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    type_proj = forms.ChoiceField(
        choices=[
            ('FC', 'Film Complet'),
            ('FAP', 'Avant-Première'),
            ('FP', 'Prochainement'),
        ],
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    class Meta:
        model = Projection
        fields = ['film', 'type_proj', 'date_proj', 'heure_proj', 'paf_proj', 'desc_proj',  'place_proj']
        widgets = {
            'date_proj': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'heure_proj': forms.TextInput(attrs={'class': 'form-control'}),
            'paf_proj': forms.TextInput(attrs={'class': 'form-control'}),
            'desc_proj': forms.TextInput(attrs={'class': 'form-control'}),
            'paf_proj': forms.TextInput(attrs={'class': 'form-control'}),
            'place_proj': forms.TextInput(attrs={'class': 'form-control'}),
        }

cinetix_project/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'password',
    }))

cinetix/views.py
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)

from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from .forms import *

class FilmListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Film
    template_name = 'cinetix/film/film_list.html'
    context_object_name = 'films'


class FilmCreateView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Film
    fields = ['titre', 'evaluation', 'genres', 'acteur', 'synopsis', 'trailer', 'posteur', 'commentaires']
    success_url = reverse_lazy('cinetix:film-list')
    

class FilmUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    model = Film
    pk_url_kwarg = 'id_film'
    fields = ['titre', 'evaluation', 'genres', 'acteur', 'synopsis', 'trailer', 'posteur', 'commentaires']
    success_url = reverse_lazy('cinetix:film-list')


class FilmDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'login'
    model =  Film
    pk_url_kwarg = 'id_film'
    success_url = reverse_lazy('cinetix:film-list')
    

class ProjListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Projection
    template_name = 'cinetix/projection/fc_list.html'
    context_object_name = 'projection'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProjectionForm()  # Ajouter le formulaire de création
        return context
    

class ProjCreateView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Projection
    form_class = ProjectionForm
    template_name = 'cinetix/projection/proj_create.html'  # Votre template HTML pour ce formulaire
    success_url = reverse_lazy('cinetix:projection-list')  # Redirige vers la liste des projections après la soumission

cinetix_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import LoginForm


@login_required(login_url='login')
def test_page(request):
    context = {
        'test': 'test',
    }
    return render(request, 'test.html', context)


def login_page(request):
    forms = LoginForm()
    if request.method == 'POST':
        forms = LoginForm(request.POST)
        if forms.is_valid():
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('cinetix:film-list')
    context = {
        'form': forms
    }
    return render(request, 'login.html', context)

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>{% block title_1 %} {% endblock title_1 %}</title>
		{% include 'base/header.html' %}
    </head>
    <body>
		<!-- Main Wrapper -->
        <div class="main-wrapper">
		
			<!-- Navbar -->
            {% include 'base/navbar.html' %}
            <!-- /.navbar -->

            <!-- Main Sidebar Container -->
            {% include 'base/sidebar.html' %}
			
			<!-- Page Wrapper -->
            <div class="page-wrapper">
			
				<!-- Page Content -->
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">{% block title_2 %} {% endblock title_2 %}</h3>
								<ul class="breadcrumb">
								<li class="breadcrumb-item">Listes</li>
									<li class="breadcrumb-item active"><a href="">{% block title_3 %} {% endblock title_3 %}</a></li>
								</ul>
							</div>
							{% block boutton_create %}

                    		{% endblock boutton_create %}
						</div>
					</div>
					<!-- /Page Header -->

					<!-- Search Filter -->
					<div class="row filter-row">
						<div class="col-sm-6 col-md-8">  
							<div class="form-group form-focus">
								<input type="text" name="search_1" id="search_1" class="form-control floating">
								<label class="focus-label">Entrer les mots clés</label>
							</div>
						</div>
                    </div>
					<!-- Search Filter -->
					
					{% block content %}

                    {% endblock content %}

                </div>
				<!-- /Page Content -->

				{% block modal_create %}

				{% endblock modal_create %}
				
            </div>
			<!-- /Page Wrapper -->

        </div>
		<!-- /Main Wrapper -->
		
		{% include 'base/js.html' %}

        {% block extrascript %}

        {% endblock extrascript %}
    </body>
</html>

templates/base/header.html
{% load static %}

<!-- Favicon -->
<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.png' %}">
		
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<!-- Fontawesome CSS -->
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

<!-- Lineawesome CSS -->
<link rel="stylesheet" href="{% static 'css/line-awesome.min.css' %}">

<!-- Select2 CSS -->
<link rel="stylesheet" href="{% static 'css/select2.min.css' %}">

<!-- Datetimepicker CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">

<!-- Main CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<!-- Metro CSS -->
<link rel="stylesheet" href="{% static 'css/metro-all.min.css' %}">

<!-- Multiple Select CSS -->
<link rel="stylesheet" href="{% static 'css/multi-select-tag.css' %}">

templates/base/js.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>

<!-- Bootstrap Core JS -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- Slimscroll JS -->
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>

<!-- Select2 JS -->
<script src="{% static 'js/select2.min.js' %}"></script>

<!-- Datetimepicker JS -->
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>

<!-- Datatable JS -->
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>

<!-- Custom JS -->
<script src="{% static 'js/app.js' %}"></script>

<!-- Recherche instantannée -->
<script src="{% static 'js/recherche.js' %}"></script>

<!-- Metro JS -->
<script src="{% static 'js/metro.min.js' %}"></script>

<!-- MultiSelectTag JS -->
<script src="{% static 'js/multi-select-tag.js' %}"></script>

templates/base/navbar.html
{% load static %}


<div class="header">
	<!-- Logo -->
	<div class="header-left">
		<a href="" class="logo">
			<img src="{% static 'img/logo.png' %}" width="53" height="40" alt="">
			<!-- <i class="fa fa-modx"></i>London Academy. -->
		</a>
	</div>
	<!-- /Logo -->
	
	<a id="toggle_btn" href="javascript:void(0);">
		<span class="bar-icon">
			<span></span>
			<span></span>
			<span></span>
		</span>
	</a>
	
	<!-- Header Title -->
	<div class="page-title-box">
		<h3>CinéTix</h3>
	</div>
	<!-- /Header Title -->
	
	<a id="mobile_btn" class="mobile_btn" href="#sidebar"><i class="fa fa-bars"></i></a>
	
	<!-- Header Menu -->
	<ul class="nav user-menu">

		<li class="nav-item dropdown has-arrow main-drop">
			<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
				<span class="user-img"><img src="{% static 'img/utilisateur/user.jpg' %}">
				<span class="status online"></span></span>
				<span>Pas d'utilisateur</span>
			</a>
			<div class="dropdown-menu">
				<a class="dropdown-item" href="">Paramètres</a>
				<a class="dropdown-item" href="">Déconnecter</a>
			</div>
		</li>
	</ul>
	<!-- /Header Menu -->
	
	<!-- Mobile Menu -->
	<div class="dropdown mobile-user-menu">
		<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
		<div class="dropdown-menu dropdown-menu-right">
			<a class="dropdown-item" href="">My Profile</a>
			<a class="dropdown-item" href="">Settings</a>
			<a class="dropdown-item" href="">Logout</a>
		</div>
	</div>
	<!-- /Mobile Menu -->
	
</div>

templates/base/sidebar.html
{% load static %}

<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                

                <li class="menu-title"> 
                    <span>Section</span>
                </li>

                <li class="submenu">
                    <a href="#"><i class="la la-dashboard"></i> <span> Films</span> <span class="menu-arrow"></span></a>
                    <ul style="display: none;">
                        <li><a href="{% url 'cinetix:film-list' %}"> -  Film enregistrer</a></li>
                        <li><a href=""> -  Film en vote</a></li>
                    </ul>
                </li>

                <li class="menu-title"> 
                    <span></span>
                </li>

                <li class="submenu">
                    <a href="#"><i class="la la-dashboard"></i> <span> Projection</span> <span class="menu-arrow"></span></a>
                    <ul style="display: none;">
                        <li><a href="{% url 'cinetix:projection-list' %}"> -  Film complet</a></li>
                        <li><a href=""> -  Avant-premiere</a></li>
                        <li><a href=""> -  Prochainemant</a></li>
                    </ul>
                </li>
                
                <li class="menu-title"> 
                    <span></span>
                </li>

                <li> 
                    <a href=""><i class="la la-barcode"></i> <span> Utilisateurs</span></a>
                </li>
                
                <li class="menu-title"> 
                    <span></span>
                </li>

                <li> 
                    <a href=""><i class="la la-barcode"></i> <span> Commentaires</span></a>
                </li>
                
                <li class="menu-title"> 
                    <span></span>
                </li>

                <li> 
                    <a href=""><i class="la la-plus"></i> <span> Réservation</span></a>
                </li>
                
                <li class="menu-title"> 
                    <span></span>
                </li>

                <li> 
                    <a href=""><i class="la la-share"></i> <span> Messages</span></a>
                </li>


                <li class="menu-title"> 
                    <span></span>
                </li>

                <li class="menu-title"> 
                    <span>Autre</span>
                </li>
                <li> 
                    <a href=""><i class="la la-cogs"></i> <span>Paramètre</span></a>
                </li>


                <li class="menu-title"> 
                    <span>Sortir</span>
                </li>
                <li> 
                    <a href=""><i class="la la-power-off"></i> <span>Déconnection</span></a>
                </li>
                        
            </ul>
        </div>
    </div>
</div>

templates/cinetix/film/film_create.html
<div id="film_create" class="modal custom-modal fade" role="dialog">
	<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Nouveau film</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form action="{% url 'cinetix:film-create' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
					<div class="row">
						<div class="col-sm-9">
							<div class="form-group">
								<label for="titre">Titre : </label>
								<input type="text" class="form-control" name="titre" id="titre">
							</div>
						</div>
                        <div class="col-sm-3">
							<div class="form-group">
								<label for="evaluation">Evaluation : </label>
								<input type="number" class="form-control" name="evaluation">
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="genres">Genres : </label>
								<input type="hidden" name="genres" id="genres">
								<select name="gg" id="gg" multiple class="form-control">
									<option value="action">Action</option>
									<option value="drama">Drama</option>
									<option value="comedy">Comedy</option>
									<option value="thriller">Thriller</option>
									<option value="horror">Horror</option>
								</select>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="acteur">Acteur :</label>
								<input type="hidden" name="acteur" id="acteur">
								<select name="aa" id="aa" multiple class="form-control">
									<option value="Jason Statham">Jason Statham</option>
									<option value="Tom Holland">Tom Holland</option>
									<option value="Gal Gadot">Gal Gadot</option>
									<option value="Tony jah">Tony jah</option>
								</select>
							</div>
						</div>
						<div class="col-sm-12">
							<div class="form-group">
								<label for="synopsis">Synopsis : </label>
								<input type="text" class="form-control" name="synopsis" id="synopsis">
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="trailer">Trailer : </label>
								<input type="file" class="form-control" name="trailer">
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="posteur">Posteur : </label>
								<input type="file" class="form-control" name="posteur">
							</div>
						</div>
						<div class="col-sm-12">
							<div class="form-group">
								<label for="commentaires">commentaires : </label>
								<input type="text" class="form-control" name="commentaires">
							</div>
						</div>
					</div>
				
					<div class="submit-section">
						<button type="submit" class="btn btn-primary submit-btn">Valider</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

templates/cinetix/film/film_delete.html
<div id="film_delete_{{ film.pk }}" class="modal custom-modal fade" role="dialog">
	<div class="modal-dialog modal-dialog-centered">
		<form action="{% url 'cinetix:film-delete' film.pk %}" method="post">
			{% csrf_token %}
            <div class="modal-content">
				<div class="modal-body-delete">
					<div class="form-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							<h3>Suppresion d'un film</h3>
							<p>Voulez vous vraiment supprimer <strong>{{ film.titre }}</strong> ?</p>
					</div>
					<div class="modal-btn delete-action">
						<div class="row">
							<div class="col-6">
								<a href="javascript:void(0);" data-dismiss="modal" class="btn btn-primary cancel-btn">Annuler</a>
							</div>
							<div class="col-6">
								<button type="submit" class="btn btn-primary continue-btn">Supprimer</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

templates/cinetix/film/film_list.html
{% extends 'base/base.html' %}
{% block title_1 %} Film {% endblock title_1 %}
{% block title_2 %} Film {% endblock title_2 %}
{% block title_3 %} Liste des films {% endblock title_3 %}

{% block boutton_create %}
<div class="col-auto float-right ml-auto">
    <a href="" class="btn add-btn" data-toggle="modal" data-target="#film_create"><i class="fa fa-plus"></i> Film </a>
</div>
{% endblock boutton_create %}

{% block content %}
<div class="row staff-grid-row">
    {% csrf_token %}
    {% for film in films %}

        <div class="col-md-4 col-sm-6 col-12 col-lg-4 col-xl-3">
            <div class="profile-widget">
                <div class="profile-img">
                    <a href="#"data-toggle="modal" data-target="#film_view_{{ film.pk }}" class="avatar"><img src="/{{film.posteur}}" alt="image"></a>
                </div>
                    <div class="dropdown profile-action">
                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="material-icons">more_vert</i></a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#film_update_{{ film.pk }}"><i class="fa fa-pencil m-r-5"></i> Modifier</a>
                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#film_delete_{{ film.pk }}"><i class="fa fa-trash m-r-5"></i> Supprimer</a>
                        </div>
                    </div>
                <div>
                    <h4 class="user-name m-t-10 mb-0 text-ellipsis">{{ film.titre }}</h4>
                    <h6 class="user-name text-muted">{{ film.genres|join:', ' }}</h6>
                    <input data-role="rating" data-value="{{ film.evaluation }}">
                </div>
            </div>
        </div>

        {% include 'cinetix/film/film_view.html' %}
        {% include 'cinetix/film/film_update.html' %}
        {% include 'cinetix/film/film_delete.html' %}
            
    {% endfor %}	
</div>
<div class="container-v">
    <div class="popup-video">
        <span>&times;</span>
        <video src="" muted autoplay controls></video>
    </div>
</div>
{% endblock content %}


{% block modal_create %}
    {% include 'cinetix/film/film_create.html' %}
{% endblock modal_create %}


{% block extrascript %}
<script>
    document.querySelectorAll('.video_btn').forEach(video_btn => {
        const video = video_btn.querySelector('input');
        const playButton = video_btn.querySelector('.fa_btn');
    
        playButton.addEventListener('click', () => {
            document.querySelector('.container-v').style.display = 'block';
            document.querySelector('.popup-video').style.display = 'block';
            document.querySelector('.popup-video video').src = video.getAttribute('value');
        });
    });

    document.querySelector('.popup-video span').onclick = () => {
        document.querySelector('.container-v').style.display = 'none';
        document.querySelector('.popup-video').style.display = 'none';
        document.querySelector('.popup-video video').muted = 'true';
    }

    new MultiSelectTag('gg', 'genres')
    new MultiSelectTag('aa', 'acteur')

    new MultiSelectTag('n_gg', 'n_genres')
    new MultiSelectTag('n_aa', 'n_acteur')
    
</script>
{% endblock extrascript %}

templates/cinetix/film/film_update.html
<div id="film_update_{{ film.pk }}" class="modal custom-modal fade" role="dialog">
	<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Nouveau film</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form action="{% url 'cinetix:film-update' film.pk %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
					<div class="row">
						<div class="col-sm-9">
							<div class="form-group">
								<label for="titre">Titre : </label>
								<input type="text" class="form-control" name="titre" value="{{ film.titre }}">
							</div>
						</div>
                        <div class="col-sm-3">
							<div class="form-group">
								<label for="evaluation">Evaluation : </label>
								<input type="number" class="form-control" name="evaluation" value="{{ film.evaluation }}">
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="genres">Genres : </label>
								<input type="hidden" name="genres" id="n_genres" value="{{ film.genres }}">
								<select name="n_gg" id="n_gg" multiple class="form-control">
									<option value="action">Action</option>
									<option value="drama">Drama</option>
									<option value="comedy">Comedy</option>
									<option value="thriller">Thriller</option>
									<option value="horror">Horror</option>
								</select>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="acteur">Acteur :</label>
								<input type="hidden" name="acteur" id="n_acteur" value="{{ film.acteur }}">
								<select name="n_aa" id="n_aa" multiple class="form-control">
									<option value="Jason Statham">Jason Statham</option>
									<option value="Tom Holland">Tom Holland</option>
									<option value="Gal Gadot">Gal Gadot</option>
									<option value="Tony jah">Tony jah</option>
								</select>
							</div>
						</div>
						<div class="col-sm-12">
							<div class="form-group">
								<label for="synopsis">Synopsis : </label>
								<input type="text" class="form-control" name="synopsis" value="{{ film.synopsis }}">
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="trailer">Trailer : </label>
								<input type="file" class="form-control" name="trailer" value="{{ film.trailer }}">
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="posteur">Posteur : </label>
								<input type="file" class="form-control" name="posteur" value="{{ film.posteur }}">
							</div>
						</div>
						<div class="col-sm-12">
							<div class="form-group">
								<label for="commentaires">commentaires : </label>
								<input type="text" class="form-control" name="commentaires" value="{{ film.commentaires }}">
							</div>
						</div>
					</div>
				
					<div class="submit-section">
						<button type="submit" class="btn btn-primary submit-btn">Valider</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

templates/cinetix/projection/proj_create.html
<div id="proj_create" class="modal custom-modal fade" role="dialog">
	<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Nouveau Projection</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form action="{% url 'cinetix:projection-create' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
					<div class="row">
						<div class="col-sm-12">
							<div class="form-group">
								<label for="{{ form.film.id_for_label }}">Film : </label>
								{{ form.film }}
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="{{ form.type_proj.id_for_label }}">Type de projection : </label>
								{{ form.type_proj }}
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="{{ form.date_proj.id_for_label }}">Date : </label>
								{{ form.date_proj }}
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="{{ form.heure_proj.id_for_label }}">Heure : </label>
								{{ form.heure_proj }}
							</div>
						</div>
						<div class="col-sm-9">
							<div class="form-group">
								<label for="{{ form.desc_proj.id_for_label }}">Description : </label>
								{{ form.desc_proj }}
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="{{ form.paf_proj.id_for_label }}">PAF : </label>
								{{ form.paf_proj }}
							</div>
						</div>
					</div>
				
					<div class="submit-section">
						<button type="submit" class="btn btn-primary submit-btn">Valider</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>